FROM ich777/steamcmd:dontstarve@sha256:9cabdfe8a422e1ebcb3dee7cf2daa91e77eff202a79ee69c0fde2aaac547d176
LABEL org.opencontainers.image.source=https://github.com/truecharts/containers
ARG CONTAINER_NAME
ARG CONTAINER_VER
LABEL org.opencontainers.image.licenses=BSD-3-Clause
LABEL org.opencontainers.image.title=${CONTAINER_NAME}
LABEL org.opencontainers.image.url=https://truecharts.org/docs/charts/${CONTAINER_NAME}
LABEL org.opencontainers.image.version=${CONTAINER_VER}
LABEL org.opencontainers.image.description=Container for ${CONTAINER_NAME} by TrueCharts
LABEL org.opencontainers.image.authors=TrueCharts
LABEL org.opencontainers.image.documentation=https://truecharts.org/docs/charts/${CONTAINER_NAME}

