FROM joey291/discordgsm:latest@sha256:d3facca9eb4a94180d7f7abaa58233bb4437c7564a51362320352f4e52be375d
LABEL org.opencontainers.image.source=https://github.com/truecharts/containers
ARG CONTAINER_NAME
ARG CONTAINER_VER
LABEL org.opencontainers.image.licenses=BSD-3-Clause
LABEL org.opencontainers.image.title=${CONTAINER_NAME}
LABEL org.opencontainers.image.url=https://truecharts.org/docs/charts/${CONTAINER_NAME}
LABEL org.opencontainers.image.version=${CONTAINER_VER}
LABEL org.opencontainers.image.description=Container for ${CONTAINER_NAME} by TrueCharts
LABEL org.opencontainers.image.authors=TrueCharts
LABEL org.opencontainers.image.documentation=https://truecharts.org/docs/charts/${CONTAINER_NAME}

