FROM ghcr.io/linuxserver/booksonic-air:2201.1.0@sha256:44c852e379cfa4f4ee6f2c0c9447cae458a88fa42d1bc6afa985af61ce2bd504
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
