FROM ghcr.io/linuxserver/booksonic-air:2201.1.0@sha256:8b126795dfc2ded42adc9cb6a7cdfb673418840cf51713606a7dfa8094602c56
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
