FROM ghcr.io/k8s-at-home/wireguard:v1.0.20210914@sha256:92b6c9af6e15f38672ab9be1d9d2c92006d2a55b11cd9acc590c2cea66e068a4
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
