FROM ghcr.io/k8s-at-home/apache-musicindex:v1.4.1-2@sha256:5e84286fe9200c7bff285fd5a7a85ec874f673da67d4d6c2b89031878929d9a3
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
