FROM ghcr.io/linuxserver/mysql-workbench:8.0.29@sha256:535ab3fb77c568dfeb298abe39651ec804cc02711895d36a2a93fe2c6f0ba23f
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
