FROM ghcr.io/linuxserver/mysql-workbench:8.0.29@sha256:49a2c83be2476025ff5ee0bd74cc90d1a58b9c5ad1abee318e85f4d2ace89fc3
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
