FROM ghcr.io/analogj/scrutiny:v0.4.15-omnibus@sha256:7b1e8c67499f2f39de25cc20ed847d627fa7720a530cf4de1c2a0b3fb19faf12
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
