FROM airsonicadvanced/airsonic-advanced:edge-latest@sha256:18de305bce05d47a885a40e6fbeecbf26ebc1ea815cedcce4be1f533a39bd3e8
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
