FROM airsonicadvanced/airsonic-advanced:edge-latest@sha256:2b7f77ac70a4c5eb3df183df650092506c8096030d3053c267f8da0b12ef08b4
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
