FROM ghcr.io/miguelndecarvalho/speedtest-exporter:v3.5.2@sha256:3853e41b44b459edddceaacf1730104c972eb2c8d94cdfbc009f4e872bba93df
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
