FROM ghcr.io/linuxserver/photoshow:version-48aabb98@sha256:20e9ecb7ff0e7a7746818efa9ea193bbdeedb6625f0375a0891a3b4a48857c00
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
