FROM zabbix/zabbix-web-nginx-pgsql:6.2.0-ubuntu@sha256:ace3e35427e2a36ac85f2ecb3567c22dbdce6f9085d334a728dad272b691e110
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
