FROM ghcr.io/linuxserver/lazylibrarian:latest@sha256:40456cfbfc92379527bcc0839abc8b87276887c132966c172e04c2b995b96ee0
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
