FROM ich777/urbanterror:latest@sha256:81aa58185403aaa8e5de22fd5917804dff0aa93deebb1d54a81ba67db98eeb3e
LABEL org.opencontainers.image.source=https://github.com/truecharts/containers
ARG CONTAINER_NAME
ARG CONTAINER_VER
LABEL org.opencontainers.image.licenses=BSD-3-Clause
LABEL org.opencontainers.image.title=${CONTAINER_NAME}
LABEL org.opencontainers.image.url=https://truecharts.org/docs/charts/${CONTAINER_NAME}
LABEL org.opencontainers.image.version=${CONTAINER_VER}
LABEL org.opencontainers.image.description=Container for ${CONTAINER_NAME} by TrueCharts
LABEL org.opencontainers.image.authors=TrueCharts
LABEL org.opencontainers.image.documentation=https://truecharts.org/docs/charts/${CONTAINER_NAME}

