FROM browserless/chrome:1.53.0-chrome-stable@sha256:376a551a8b2dcaf8f8fe6d3fc36e8ed2257c41e9e2e4ede763e9a0ac8195c753
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
