FROM ghcr.io/linuxserver/quassel-core:0.14.0@sha256:5ee1abe9c5ff73c618829b16b6af311fb4d8c7e1461bc9f4078c5f6a88ce3b8a
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
