FROM ghcr.io/linuxserver/muximux:version-057352e8@sha256:3065b039975e9b58b0cba4c19b63c5453bd80ad9911a4baa2bfca77190a7eea0
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
