FROM ghcr.io/linuxserver/airsonic:version-v10.6.2@sha256:0a0e49be383db9340c0a8258bb31c5916281ec18c8c3fb56006866d18f8e63e0
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
