FROM reallibrephotos/librephotos-proxy:latest@sha256:7f1bd04561ca1d71c5e526bd05c3ea7fc6c08334de42deb6710a99ff6d5200f5
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
