FROM reallibrephotos/librephotos-proxy:latest@sha256:459719be71d3f4db0d6acf5f755bbb2713f43f7a6c543778e314bdd89264fac8
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
