FROM ghcr.io/linuxserver/openvscode-server:1.67.1@sha256:086f04dbbef1e980aed5062bde4f2f2b1c83b1b074255ae3c87ec110a3b48b6f
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
