FROM ghcr.io/linuxserver/cloud9:version-1.29.2@sha256:98ae28b73428fabae8c70d06287314be98ac8261c118d920e4f963b03cbbbadd
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
