FROM ghcr.io/linuxserver/cloud9:version-1.29.2@sha256:8a1725bd0e415bc492e4af5304cf2838770e242df074fa2c9251a8dc7ed0a721
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
