name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@e24c028a6d3b903b79320c97e89e4e9bd7055054 # v34.42.0
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.BOT_TOKEN }}
