name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@f65d704dc047d296dba50b502af53c4ae186e49f # tag=v34.10.0
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.BOT_TOKEN }}
