---
name: "Schedule: Sync labels"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@7dd9e2a3dc350cf687eb1b2a4fadfee8c8e49675 # v3
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Sync Labels
        uses: EndBug/label-sync@da00f2c11fdb78e4fae44adac2fdd713778ea3e8 # v2
        with:
          config-file: |
              https://raw.githubusercontent.com/truecharts/.github/main/.github/labels.yaml
          token: "${{ secrets.BOT_TOKEN }}"
          delete-other-labels: true
